package model;

enum TipoMelhoria {
    MOEDA_VIRTUAL,
    ESPADA_VIRTUAL,
    YURT_VIRTUAL,
    PEGAR_TRIBUTO_EXTRA,
    MOVIMENTO_EXTRA,
    BOI_VIRTUAL,
    FERRO_VIRTUAL,
	PELE_VIRTUAL,
	TECIDO_VIRTUAL,
	ALIMENTO_VIRTUAL
    
}
