package model;

enum TipoConselheiroAberto {
	QUATRO_ESPADAS,
	SEIS_YURTS, 
	DEZ_YURTS, 
	QUATRO_TESOUROS,
    CINCO_TESOUROS_DIFERENTES,
    UM_YURT_POR_REGIAO,
    DOIS_YURTS_POR_REGIAO,
    DUAS_PECAS_BONUS, 
    TRES_PECAS_BONUS,
    CONQUISTAR_DUAS_CIDADES,
    CONQUISTAR_TRES_CIDADES,
    LINHA_DE_MELHORIAS,
    DUAS_COLUNAS_COM_DUAS_MELHORIAS, 
    QUATRO_MELHORIAS_NA_COLUNA
    
}
